// Stage 4C: deterministic PNG -> JPEG publishing-derivative pipeline for
// the already-approved Feed (4:5) artwork. This module NEVER uploads
// anything, NEVER touches R2, and NEVER regenerates or redesigns the
// artwork itself — it only re-encodes the exact approved pixels (or
// refuses to, if it can't do so safely) into the format Instagram's
// media-container API requires. The PNG remains the canonical approved
// artwork forever; the JPEG produced here is a disposable publishing
// convenience that can always be regenerated byte-for-byte from it.
//
// Reuses the SAME Feed aspect-ratio/dimension constants artworkValidation.js
// already validates the approved PNG against — one source of truth, not a
// second set of "close enough" numbers for JPEG.
import sharp from "sharp";
import { ASPECT_RATIO_TARGET, ASPECT_RATIO_TOLERANCE, MIN_DIMENSION } from "../../lib/artworkValidation.js";

const JPEG_QUALITY = 92;
const STORAGE_KEY_SAFE_ID = /^[a-zA-Z0-9-]+$/;

/**
 * Deterministic storage key for a story's Feed JPEG derivative. Rejects
 * anything that isn't a plain story_id-shaped string, so one story's key
 * can never accidentally collide with, or path-traverse into, another's.
 */
export function deriveJpegStorageKey(storyId) {
  if (typeof storyId !== "string" || !STORAGE_KEY_SAFE_ID.test(storyId)) {
    throw new Error(`deriveJpegStorageKey: unsafe or empty story_id: ${JSON.stringify(storyId)}`);
  }
  return `social-artwork-jpeg/${storyId}.jpg`;
}

/**
 * Alpha-channel inspection — the load-bearing safety check before any
 * flatten/fill decision is made. A PNG with no alpha channel at all, or an
 * alpha channel that is fully opaque everywhere (min value 255 across the
 * whole image), has nothing for a background-fill color to ever visibly
 * affect. A PNG with genuine partial/full transparency does — and this
 * function's ONLY job is telling the two cases apart, never deciding what
 * to do about it.
 */
export async function inspectAlpha(pngBuffer) {
  const image = sharp(pngBuffer);
  const metadata = await image.metadata();
  if (!metadata.hasAlpha) {
    return { hasAlphaChannel: false, fullyOpaque: true };
  }
  const { channels } = await image.stats();
  const alphaChannel = channels[channels.length - 1];
  return { hasAlphaChannel: true, fullyOpaque: alphaChannel.min === 255 };
}

/**
 * Converts an already-approved Feed PNG buffer into a deterministic JPEG
 * buffer. Applies NO resize, NO crop, and NO redesign — every pixel is
 * re-encoded exactly as-is (modulo JPEG's own lossy compression), at fixed
 * quality, with metadata stripped (sharp never carries EXIF/ICC forward
 * unless `.withMetadata()` is explicitly called, which this never does).
 *
 * Fails closed (does not silently pick a background color) if the source
 * has GENUINE transparency and no `backgroundFillPolicy` was supplied —
 * see inspectAlpha's doc comment. A caller must explicitly decide and pass
 * a fill policy for that case; this function will never guess one.
 * @param {Buffer} pngBuffer
 * @param {{backgroundFillPolicy?: {r:number,g:number,b:number}}} [opts]
 * @returns {Promise<{ok:true, buffer:Buffer}|{ok:false, error:string}>}
 */
export async function convertToJpegDerivative(pngBuffer, { backgroundFillPolicy } = {}) {
  const alpha = await inspectAlpha(pngBuffer);

  if (alpha.hasAlphaChannel && !alpha.fullyOpaque && !backgroundFillPolicy) {
    return { ok: false, error: "transparency_requires_fill_policy" };
  }

  // A fill color is still structurally required to flatten the alpha
  // channel out for JPEG even when every pixel is already fully opaque —
  // it is simply guaranteed never to be visible in that case, so an
  // unspecified default (white) is safe there. Genuine transparency always
  // uses the caller-approved policy, never this default.
  const background = alpha.hasAlphaChannel && !alpha.fullyOpaque ? backgroundFillPolicy : backgroundFillPolicy ?? { r: 255, g: 255, b: 255 };

  const buffer = await sharp(pngBuffer)
    .flatten({ background })
    .jpeg({ quality: JPEG_QUALITY, mozjpeg: true })
    .toBuffer();

  return { ok: true, buffer };
}

// How far inside each edge to sample, avoiding a 1-pixel anti-aliased
// canvas-edge ring (a common PNG-export artifact — a very slight
// feather/rounding bleed on the outermost pixels) that would otherwise
// contaminate a literal (0,0)-style corner read.
const CORNER_SAMPLE_INSET = 8;
// Small enough to reject a genuine gradient/multi-tone background, generous
// enough to tolerate ordinary compression/dithering noise in a flat fill.
const CORNER_AGREEMENT_TOLERANCE = 24;

/**
 * Deterministically derives a single background-fill RGB from the approved
 * PNG's own four corners — used ONLY when the source has genuine partial
 * transparency and no fixed template background color is known (see
 * resolveApprovedFeedJpeg.js). Never guesses: if any sampled corner is
 * itself non-opaque, or the four corners don't agree within a small
 * tolerance (e.g. a real gradient/lighting design, not a flat background),
 * this returns null — the caller must fail closed
 * (background_fill_ambiguous), never silently default to white or black.
 * @param {Buffer} pngBuffer
 * @returns {Promise<{r:number,g:number,b:number}|null>}
 */
export async function deriveCornerBackgroundFill(pngBuffer) {
  const { data, info } = await sharp(pngBuffer).ensureAlpha().raw().toBuffer({ resolveWithObject: true });
  const { width, height, channels } = info;
  const inset = Math.min(CORNER_SAMPLE_INSET, Math.floor(width / 2) - 1, Math.floor(height / 2) - 1);
  if (inset < 0) return null;

  function pixelAt(x, y) {
    const idx = (y * width + x) * channels;
    return { r: data[idx], g: data[idx + 1], b: data[idx + 2], a: data[idx + 3] };
  }

  const corners = [
    pixelAt(inset, inset),
    pixelAt(width - 1 - inset, inset),
    pixelAt(inset, height - 1 - inset),
    pixelAt(width - 1 - inset, height - 1 - inset),
  ];

  if (corners.some((c) => c.a !== 255)) return null;

  const [first, ...rest] = corners;
  const agrees = rest.every(
    (c) =>
      Math.abs(c.r - first.r) <= CORNER_AGREEMENT_TOLERANCE &&
      Math.abs(c.g - first.g) <= CORNER_AGREEMENT_TOLERANCE &&
      Math.abs(c.b - first.b) <= CORNER_AGREEMENT_TOLERANCE
  );
  if (!agrees) return null;

  const avg = (key) => Math.round(corners.reduce((sum, c) => sum + c[key], 0) / corners.length);
  return { r: avg("r"), g: avg("g"), b: avg("b") };
}

const JPEG_MAGIC_BYTES = Buffer.from([0xff, 0xd8, 0xff]);

/**
 * Strict validation of a produced JPEG derivative before it is ever handed
 * to a Meta client. Checks format/dimensions/aspect-ratio/magic-bytes
 * exactly, plus a lightweight visual-equivalence check against the source
 * PNG to catch gross conversion corruption — NOT a pixel-perfect
 * comparison, which would be an unrealistic bar for a lossy format.
 * @param {Buffer} jpegBuffer
 * @param {Buffer} pngBuffer - the exact source the JPEG was derived from
 * @param {{expectedWidth?: number, expectedHeight?: number}} [opts]
 */
export async function validateJpegDerivative(jpegBuffer, pngBuffer, { expectedWidth = 1024, expectedHeight = 1280 } = {}) {
  const issues = [];

  if (!jpegBuffer || jpegBuffer.length === 0) {
    return { passed: false, issues: ["empty_buffer"] };
  }
  if (!jpegBuffer.subarray(0, 3).equals(JPEG_MAGIC_BYTES)) {
    issues.push("invalid_magic_bytes");
  }

  let metadata;
  try {
    metadata = await sharp(jpegBuffer).metadata();
  } catch {
    return { passed: false, issues: [...issues, "unreadable_image"] };
  }

  if (metadata.format !== "jpeg") issues.push(`unexpected_format:${metadata.format}`);
  if (metadata.width !== expectedWidth || metadata.height !== expectedHeight) {
    issues.push(`unexpected_dimensions:${metadata.width}x${metadata.height}`);
  }
  if (metadata.width && metadata.height) {
    const ratio = metadata.width / metadata.height;
    if (Math.abs(ratio - ASPECT_RATIO_TARGET) > ASPECT_RATIO_TOLERANCE) {
      issues.push(`aspect_ratio_out_of_range:${ratio.toFixed(3)}`);
    }
    if (metadata.width < MIN_DIMENSION || metadata.height < MIN_DIMENSION) {
      issues.push("insane_dimensions");
    }
  }

  const visualIssue = await checkVisualEquivalence(pngBuffer, jpegBuffer);
  if (visualIssue) issues.push(visualIssue);

  return { passed: issues.length === 0, issues };
}

/**
 * Compares mean per-channel brightness (R/G/B only — JPEG has no alpha) of
 * the source PNG against the produced JPEG. A correct re-encode of the
 * same image, even at lossy JPEG quality, stays within a few units of the
 * original's channel means; a genuinely wrong/corrupted/blank image does
 * not. This is a coarse "did something go badly wrong" signal, never a
 * claim of visual identity.
 */
async function checkVisualEquivalence(pngBuffer, jpegBuffer, { tolerance = 12 } = {}) {
  const [pngStats, jpegStats] = await Promise.all([sharp(pngBuffer).flatten({ background: { r: 255, g: 255, b: 255 } }).stats(), sharp(jpegBuffer).stats()]);
  for (let i = 0; i < 3; i++) {
    const pngMean = pngStats.channels[i]?.mean;
    const jpegMean = jpegStats.channels[i]?.mean;
    if (pngMean === undefined || jpegMean === undefined) return "visual_equivalence_check_failed";
    if (Math.abs(pngMean - jpegMean) > tolerance) return `visual_equivalence_out_of_range:channel${i}`;
  }
  return null;
}
